# Rust format configuration file
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
indent_style = "Visual"
control_brace_style = "AlwaysNextLine"
use_small_heuristics = "Max"
brace_style = "AlwaysNextLine"
where_single_line = true
imports_indent = "Visual"
trailing_comma = "Never"
overflow_delimited_expr = true
max_width = 110
reorder_modules = false
reorder_imports = false
